/**
 * BlogView - Release announcements and feature updates
 * 
 * Blog posts are auto-discovered from _posts/ via Jekyll.
 * Metadata is fetched from /blog/posts.json (auto-generated by Jekyll).
 */

const BlogView = {

  // Cached posts from /blog/posts.json (loaded on first render)
  posts: null,
  _postsPromise: null,

  /**
   * Fetch the blog posts manifest from Jekyll-generated JSON.
   * Caches after first load.
   */
  async loadPosts() {
    if (this.posts) return this.posts;
    if (this._postsPromise) return this._postsPromise;
    
    this._postsPromise = (async () => {
      try {
        const response = await fetch('/blog/posts.json', { cache: 'no-cache' });
        if (!response.ok) throw new Error('Failed to load blog posts');
        this.posts = await response.json();
        return this.posts;
      } catch (e) {
        console.error('[BlogView] Error loading posts.json:', e);
        this.posts = [];
        return this.posts;
      }
    })();
    
    return this._postsPromise;
  },

  /**
   * Check if a slug is a known blog post (for URL routing).
   * Returns true if the slug matches a post in the manifest.
   */
  async isPostSlug(slug) {
    const posts = await this.loadPosts();
    return posts.some(p => p.slug === slug);
  },

  /**
   * Render the blog view
   */
  render(state, derived, container) {
    // Show loading state while posts.json loads
    container.innerHTML = `
      <div class="blog-view">
        <header class="blog-header">
          <h1>Blog</h1>
          <p class="blog-subtitle">Articles, research, and updates from the Time-Tested project.</p>
        </header>
        <div class="blog-posts">
          <div class="loading">Loading posts...</div>
        </div>
      </div>
    `;
    
    this.loadPosts().then(posts => {
      const postsContainer = container.querySelector('.blog-posts');
      if (!postsContainer) return;
      
      if (posts.length === 0) {
        postsContainer.innerHTML = '<p>No posts yet.</p>';
        return;
      }
      
      postsContainer.innerHTML = posts.map(post => this.renderPostCard(post)).join('');
    });
  },

  /**
   * Render a single blog post card (expanded by default for now)
   */
  renderPostCard(post) {
    const imageHtml = post.image
      ? `<img class="blog-post-image" src="${post.image}" alt="${post.title}" style="width:100%; border-radius:8px; margin-bottom:12px; border:1px solid var(--border-subtle);">`
      : '';
    // Card content: use card_content HTML if available, otherwise show summary + read link
    let cardBody;
    if (post.content) {
      // Post has inline card content (from frontmatter card_content field)
      cardBody = `
        <p class="blog-post-summary">${post.summary || ''}</p>
        <div class="blog-post-content">${post.content}</div>
      `;
    } else if (post.hasContent) {
      // Post has a full article — show summary and read link
      cardBody = `
        <p class="blog-post-summary">${post.summary || ''}</p>
        <p class="blog-nav-link">
          <button onclick="AppStore.dispatch({type:'SET_VIEW',view:'reader',params:{contentType:'blog',slug:'${post.slug}'}})">Read more &rarr;</button>
        </p>
      `;
    } else {
      cardBody = `<p class="blog-post-summary">${post.summary || ''}</p>`;
    }
    
    return `
      <article class="blog-post" id="post-${post.slug}">
        ${imageHtml}
        <div class="blog-post-meta">
          <time class="blog-post-date">${post.date}</time>
        </div>
        <h2 class="blog-post-title">${post.hasContent ? `<a href="#" onclick="event.preventDefault();AppStore.dispatch({type:'SET_VIEW',view:'reader',params:{contentType:'blog',slug:'${post.slug}'}})">${post.title}</a>` : post.title}</h2>
        ${cardBody}
      </article>
    `;
  }
};

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
  module.exports = BlogView;
}
